# Generated by Django 4.2.4 on 2023-08-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='l_description',
            field=models.TextField(max_length=200, verbose_name='Hotel Description'),
        ),
        migrations.AlterField(
            model_name='location',
            name='l_name',
            field=models.CharField(max_length=50, verbose_name='Hotel Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='l_summery',
            field=models.TextField(max_length=300, verbose_name='Hotel Summary'),
        ),
        migrations.AlterField(
            model_name='location',
            name='l_tagline',
            field=models.CharField(max_length=150, verbose_name='Hotel Tagline'),
        ),
    ]
